#'Description here..
#'
#'@param n_tot ...
#'@param n_suc ...
#'@param gamma ...
#'@details ...
#'
#'@export bbb_pvalue
bbb_pvalue <- function(n1_tot, n2_tot, gamma, n1_suc, n2_suc, p_step) {
  .bbb_pvalue(n1_tot, n2_tot, gamma, n1_suc, n2_suc, p_step)
}
