# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bscCI <- function(n_tot, n_suc, conf) {
    .Call(`_fastCI_bscCI`, n_tot, n_suc, conf)
}

.cpCI <- function(n_tot, n_suc, conf) {
    .Call(`_fastCI_cpCI`, n_tot, n_suc, conf)
}

